packages/react/package-lock.json
packages/react/src/T.jsx

During the rewrite to use `@transifex/native` instead of `@transifex/core`, the live re-render functionality was dropped. This PR reintroduces it.
I have tested this on a local project by copy-pasting the `src/T.jsx` file.

Make T component rerender on language change

---

packages/native/src/TxNative.js
packages/native/src/utils.js
packages/native/tests/t.test.js
packages/native/tests/utils.test.js

During pushing, when we capture a simple pluralized ICU string, the CDS
will push it to transifex like a pluralized string:
js app -> cds: {cnt, plural, one {ONE} other {OTHER}}
cds -> APIv3:  {..., strings: {one: "ONE", other: "OTHER"}, ...}
During pulling, the CDS will format the pluralized string back to an ICU
pluralized string. Unfortunately, the variable name has been lost by
this point, so CDS will replace it with '???'
cds -> js app's cache: {???, plural, one {ΕΝΑ} other {ΑΛΛΟ}}
When rendering a translation, we expect the source string's key to match
the one in the cache and we can extract the variable name to the source
string. So before we feed the translation to the MessageFormat library,
we replace '???' with the variable name:
```javascript
t('{cnt, plural, one {ONE} other …
```

Handle plural strings from CDS

---

.gitignore
packages/native/src/index.d.ts
packages/react/src/index.d.ts

Bare-minimum declaration files for `@transifex/native` and `@transifex/react`. This is so that typescript projects don't throw errors.
To test this:
1. Create a new typescript-react project with `npx create-react-app typescript-demo --template typescript`
2. Add some code to `src/App.tsx` that uses `@transifex/native` and `@transifex/react`
- If you want, for this purpose you can copy-paste the `App.js` and `index.css` files from [txnative-sandbox/react](/transifex/transifex-native-sandbox/tree/master/reactjs/src)
_Note: In order for this to work, this branch should be merged and released first. This cannot be done for reviewing purposes. Perhaps a `npm link` in the `packages/native` and `packages/react` folders will do the trick. Otherwise, you could copy the entire `packages/native/src` …

Bare-minimum typescript declarations

---

packages/react/README.md
packages/react/src/hooks/useT.js
packages/react/src/utils/translateWithElements.jsx
packages/react/tests/T.test.jsx

Code like this will be possible:
```javascript
<T
_str="A {button} and a {bold} walk into a bar"
button={<button><T _str="button" /></button>}
bold={<b><T _str="bold" /></b>} />
```
This will render like this in English:
```html
A <button>button</button> and a <b>bold</b> walk into a bar
```
And like this in Greek:
```html
Ένα <button>κουμπί</button> και ένα <b>βαρύ</b> μπαίνουν σε ένα μπαρ
```
Assuming the translations look like this:
| source                                  | translation                                      |
|-----------------------------------------|--------------------------------------------------|
| A {button} and a {bold} walk into a bar | Ένα {button} και ένα {bold} μπαίνουν σε ένα μπαρ |
| button                                  | κουμπί …

Interpolation of react elements in T component

---

packages/native/src/TxNative.js
packages/native/tests/t.test.js

There is an initial issue in @transifex/react in which if for some reason there was a component that had something different than string for "translation" there would result to an error (caused by the react library):
```
<T _str={somevariable} somevariable={3}>
```
This change will result to `t` function always returning a string regardless of the user's input. This way any other recipient should only handle strings instead of implementing something per case.

Make `t` always return a String

---

packages/native/src/policies/PseudoTranslationPolicy.js
packages/native/tests/policies.test.js

Currently the pseudotranslation policy in the native package will
convert all characters it finds. This means that the __txnative__ words
used to handle react interpolation are also converted, which completely
removes the interpolation functionality.
This commit introduces a new policy specifically in the react package
which allows this functionality to continue to work, by purposely not
coverting any instance of "__txnative__".
This was introduced in the react package because the native package
should have no concept of the react package, and so the only reasonable
way to handle this is to introduce a react-specific policy to handle
this.
- I understand that I'm introducing a new concept of policies in the react package. Happy to discuss whether this is the right approach, but it seemed …

Introduce pseudotranslation react policy

---

.travis.yml
package.json

`package-lock.json` is on `.gitignore` file, however when releasing a new version using `lerna`, it complains about lock files that are created during local development. So in order to release, you need to manually remove `package-lock.json` from the libraries and retry.
This PR is putting the deletion of lock files as part of the `npm run release` command.

Remove package-lock.json when releasing

---

packages/native/README.md
packages/native/src/TxNative.js
packages/native/tests/tx.test.js

- Remove appLocales from init
- Remove sourceLocale from init
- Remove getAppLocales
- Remove getSupportedLocales
- Remove isSource
- Rename getRemoteLocales to getLocales
- Make getLanguages immutable
- Make getLocales immutable

Treat source language as target language

---

packages/cli/README.md
packages/cli/src/api/extract.js
packages/cli/src/api/invalidate.js
packages/cli/src/commands/invalidate.js
packages/cli/src/commands/push.js
packages/cli/test/api/extract.test.js
packages/cli/test/commands/invalidate.test.js
packages/cli/test/commands/push.test.js
packages/cli/test/fixtures/tags.js

Update CLI with the following changes:
- Rename `--tags` option to `--append-tags` to make it more descriptive what this flag does (breaking change)
- Add `--with-tags-only` flag to filter in for push only strings with specific tags
- Add `--without-tags-only` flag to filter out for push only strings without specific tags
- Add `txjs-cli invalidate` command as a helper to invalidate CDS cache

CLI: Filter content by tags, add invalidate command

---

packages/react/README.md
packages/react/package.json
packages/react/src/components/LanguagePicker.jsx
packages/react/src/hooks/useLanguages.js
packages/react/tests/LanguagePicker.test.jsx

There is no need to append the source language manually in the LanguagePicker component after the `0.9.0` version.

Remove source lang from React LanguagePicker

---

packages/react/src/utils/translateWithElements.jsx
packages/react/tests/useT.test.jsx

Addresses the issue in #48 for useT.
I case no `props` passed to the function it would break. We were missing a check/or a default on the `props` value.
The tests added are identical to the `T` component, since the result of these two should be identical.

Fix issue with useT

---

packages/cli/src/api/extract.js
packages/cli/test/fixtures/simple.js
packages/cli/test/fixtures/variables.js

This PR fixes a small issue with parsing string expressions when calling `t()` function.
Currently, empty string (which often is part of a longer string) will be incorrectly recognized as `false` thus causing the whole string to be rejected. This can cause hard to debug problems where `t('' + 'a')` will fail, but `t(' ' + 'a')` will succeed.
On top of that I'm fixing small inconsistency between the translation methods available - namely, `t() / useT()` accepts empty string and extracts it, but `<T> / <UT>` checks if `_str=` parameter is empty and skips the extraction in that case.
This PR will reject empty strings (or binary expressions which resolve to empty strings) when passed to `t()`.

Support transitional empty strings in expressions, but do not collect them

---

packages/native/src/index.d.ts

This PR just adds additional types to the native package. When trying to use `PseudoTranslationPolicy` in my typescript project, I was unable to due to this, so I figured I'd add it here.
Please let me know if there's anything I'm missing in adding these!

Add types for native exports

---

packages/angular/projects/tx-native-angular-sdk/README.md
packages/angular/projects/tx-native-angular-sdk/src/lib/interfaces.ts
packages/angular/projects/tx-native-angular-sdk/tests/translation.service.spec.ts
packages/native/README.md
packages/native/package.json
packages/native/src/TxNative.js
packages/native/src/index.d.ts
packages/native/src/index.js
packages/native/src/renderers/MessageFormatRenderer.js
packages/native/tests/renderer.test.js
packages/react/package.json

Decouple MessageFormat library from Native, add an interface to override default renderer and create custom implementations for advanced use cases.
Related to #60

Introduce abstract StringRenderer class

---

packages/cli/src/api/extract.js
packages/cli/test/api/extract.test.js
packages/cli/test/fixtures/react.jsx

Add CLI support for detecting expressions such as:
```
const text = "Hello";
return <T _str={text} />;
```
Related to #61

CLI: Detect _str const literals on T components

---

packages/cli/src/api/extract.js
packages/cli/test/api/extract.test.js
packages/cli/test/commands/push.test.js
packages/cli/test/fixtures/simple.js
packages/cli/test/fixtures/variables.js

Hi!
I created some PoC for supporting ES6 template literals. It should support basic interpolations as covered by current variable lookups.
I thought cooked strings are not suitable for this usecase, but please edit if you think cooked one is more appropriate. The differences are stated [here](https://exploringjs.com/impatient-js/ch_template-literals.html#template-strings-cooked-vs-raw).

CLI: Extract value from template literals

---

packages/angular/projects/tx-native-angular-sdk/src/lib/TXNative.module.ts

Importing TxNativeModule multiple times (multiple modules) gives error about BrowserModule loaded multiple times.
This just puts in CommonModule instead of BrowserModule.

Angular SDK: Use CommonModule and not BrowserModule

---

packages/cli/src/api/extract.js

Forgot to add a try/catch. 
When TranslatePipe has params that can not be found in current scope it will still allow the string to be pushed to Transifex.
Noticed you already did a release so I apologise :(

CLI: try/catch parsing params

---

packages/angular/projects/tx-native-angular-sdk/src/lib/T.component.ts

Spreading the vars into actualVars should avoid any trouble when
someone does not provide the correct value.
In fact, Angular should do that as well. At least mine does.
This way we can get 100% on tests as there is no hidden branches.
I notices _vars was not an allowed name. I called it `actualVars`, any name change to conform to your style guide is welcome :)

Angular SDK: move vars to get/set

---

packages/cli/README.md
packages/cli/src/api/extract.js
packages/cli/src/api/invalidate.js
packages/cli/src/api/merge.js
packages/cli/src/api/upload.js
packages/cli/src/commands/invalidate.js
packages/cli/src/commands/push.js
packages/cli/test/api/extract.test.js
packages/cli/test/api/merge.test.js
packages/cli/test/commands/invalidate.test.js
packages/cli/test/commands/push.test.js
packages/native/src/TxNative.js

Make SDK compatible with related [breaking changes](https://github.com/transifex/transifex-delivery/releases/tag/0.14.0) on CDS service:
- CLI: Enable async push of content and poll for upload results
- CLI: Update invalidation/purge responses related to new CDS version
- Add "Accept-version: v2" header on all requests to CDS

Support for CDS API v2

---

packages/cli/src/api/extract.js
packages/cli/test/api/extract.test.js
packages/cli/test/fixtures/angular-template.html

This one just adds a fallback for _context (context), _comment (comment), _charlimit (charlimit) and _tags (tags) so that usage of T and UT will get it's params out.
According to the documentation for Angular the params are without _ on the Angular T / UT component. This was handled for key but not for the other ones that are sent to Transifex. I should have seen it before :(
Includes one test to check that it does correct for _context, the rest just follows the same logic.

extract: T/UT is supposed to have no underscore in attributes

---

packages/angular/projects/tx-native-angular-sdk/src/lib/T.component.ts
packages/angular/projects/tx-native-angular-sdk/tests/T.component.spec.ts

Any change to Input() was ignored. This just changes translationParams
to a getter so that it gets what the component has set at the time of
translation.

Angular SDK: T component should get params each time

---

packages/react/README.md
packages/react/src/components/T.jsx
packages/react/src/components/UT.jsx
packages/react/src/hooks/useT.js
packages/react/tests/useT.test.js

Note: This is a breaking change and should be communicated as such!!! Fortunately, I doubt many users are using 'useT' at the moment so we should be ok.
The previous 'useT' implementation returned the translated string. The problem was that, since it's a hook, it must be used at the top of a component before any control flows. So this would be dangerous:
```javascript
function AComponent({ ... }) {
if (something) {
doSomething();
} else {
doSomethingElse();
}
const message = useT(...);
return <b>{message}<b>
}
```
since if any hooks are used in the if/else block, it would affect the order with which the hooks are used. In fact, I suspect that eslint can raise an error if the above snippet is used.
This implementation:
1. Forces the current component to rerender when the language changes …

'useT' hook to return function

---

packages/native/package.json

Using "module" field in package.json of @transifex/native is causing issues because the code is using 2 constants set by Webpack DefinePlugin. 
This creates compilation problems in Webpack configurations that are using tree-shaking with Native libraries.

Remove "module" definition from package.json

---

packages/cli/src/commands/push.js
packages/cli/test/commands/push.test.js
packages/native/src/renderers/MessageFormatRenderer.js
packages/native/tests/renderer.test.js

**@transifex/native**
We were using a single MessageFormat class instance for the entire runtime, defaulting to English locale. This has an issue when trying to use an ICU phrase with dates, e.g. `Date is {d, date, long}`.
This PR fixes the issue by creating a MessageFormat instance per locale. Now, dates are properly localized internally by the MessageFormat library.
**@transifex/cli**
Minor improvement to avoid showing the key when it is the same as source in verbose mode `txjs-cli push -v`

Add Messageformat date/time localization support

---

packages/cli/src/api/parsers/babel.js
packages/cli/test/api/extract.hashedkeys.test.js
packages/cli/test/api/extract.sourcekeys.test.js
packages/cli/test/fixtures/typescript.ts

Fixes this bug: https://github.com/transifex/transifex-javascript/issues/107

Fix cli push angular decorator

---

packages/native/README.md
packages/native/src/TxNative.js
packages/native/src/index.d.ts
packages/native/src/index.js
packages/native/tests/instance.test.js
packages/react/README.md
packages/react/src/components/LanguagePicker.jsx
packages/react/src/components/TXProvider.jsx
packages/react/src/context/TXNativeContext.jsx
packages/react/src/hooks/useLanguages.js
packages/react/src/hooks/useLocale.js
packages/react/src/hooks/useT.js
packages/react/src/hooks/useTX.js
packages/react/src/hooks/useTranslations.js
packages/react/src/index.d.ts
packages/react/src/index.js
packages/react/src/utils/translateWithElements.jsx
packages/react/tests/useLanguages.test.js
packages/react/tests/useTX.test.js

This change comes in two parts:
* TX Native library work with multiple tokens
Since right now we exposed only the singleton tx developers couldn't
initialize and use a second instance of Native.
To solve this we now expose TxNative so anyone can do a
```js
import { createNativeInstance } from '@transifex/native';
const tx1 = createNativeInstance();
tx1.init({
token: '...'
});
tx1.t('a string to translate');
```
To have synced state when someone changes a language in the main `tx`
instance the developer needs to user `tx` as controller of the instance.
```js
import { tx, createNativeInstance } from '@transifex/native';
const tx1 = createNativeInstance();
tx1.init({
token: '...',
});
tx.init({
token: '...',
})
tx.controllerOf(tx1);
```
* The React SDK part
We created a Provider in order to …

Add ability to use multiple TX Native instances

---

packages/cli/package.json
packages/cli/src/commands/invalidate.js
packages/cli/src/commands/push.js
packages/cli/test/fixtures/variables.js

Continuation of work done in #112 
The `colors` package is no longer maintained and a weird background
story.
Previous maintainers created a new fork of the package.
https://github.com/Marak/colors.js/issues/340

Drop `colors` in favor of `@colors/colors`

---

packages/native/README.md
packages/native/src/TxNative.js
packages/native/tests/tx.test.js

When TxNative is requesting content or languages from CDS, it is gracefully handling `202` responses from CDS, instructing the SDK to retry later, because content is not ready.
But, if for any reason CDS takes too long to warm-up it's content, the SDK is stuck in an infinite loop waiting for a `200` or error response from CDS.
This PR is adding more control, so that the developer can control the behaviour of this functionality by offering two new parameters for the `tx.init(..)` function:
- `fetchTimeout`: a setting to control the time in msec, after which, the `tx.getLocales()`, `tx.setCurrentLocale()` and `tx.fetchTranslations()` will throw a timeout error.
- `fetchInterval`: a setting to add a delay (250msec by default) on the polling mechanism to CDS, to avoid doing exhaustive …

Add fetch content timeout parameters

---

packages/angular/projects/tx-native-angular-sdk/src/lib/translation.service.ts
packages/cli/src/commands/push.js

`shelljs.pwd()` returns the absolute paths with backslashes on
Windows,  while the glob package works only with forward
slashes.
The fix here was to replace backslashes with forward slashes when the
whole path was set.

Fix "glob" issue with windows paths

---

packages/api/package.json
packages/api/src/transifexApi.d.ts
packages/jsonapi/src/resources.js

How to test:
1. Checkout this branch
2. `cd <path-to-repo>/packages/api`
3. `npm run build`
4. `npm link`
5. `cd <path-to-empty-folder`
6. `npm link @transifex/api`
7. Open `index.js` in vscode and type:
```javascript
const { transifexApi } = require('@transifex/api');
transifexApi.setup({ auth: 'XXX' });
async function main() {
const page = transifexApi.Organization.list();
await page.fetch();
console.log(page.data);
}
main();
```
While observing what auto-completions the editor offers. After `transifexApi.` the editor should offer all API resource types registered with the SDK.

Rudimentary code-completion in transifex/api

---

packages/cli/bin/run
packages/cli/package.json
packages/cli/src/commands/invalidate.js
packages/cli/src/commands/push.js
packages/cli/src/index.js

Update @transifex/cli to use `@oclif/core` instead of the older deprecated oclif libraries.
Also drops the unsupported [cli-ux](https://www.npmjs.com/package/cli-ux) library.
Changes are following the [official migration guide](https://github.com/oclif/core/blob/main/MIGRATION.md).

@transifex/cli: Migrate to @oclif/core

---

packages/cli/README.md
packages/cli/src/api/upload.js
packages/cli/src/commands/push.js
packages/cli/test/commands/push.test.js

Make use of CDS dry_run meta flag when pushing content, and emulate the push command without actually applying changes in the Transifex content.

@transifex/cli Add support for server-side dry run

---

packages/cli/README.md
packages/cli/src/api/download.js
packages/cli/src/api/utils.js
packages/cli/src/commands/pull.js
packages/cli/test/commands/pull.test.js

Add a "pull" command in the CLI, to allow pulling content for offline/warming-up content when needed, e.g. on React Native mobile apps.

@transifex/cli Add pull command for offline caching

---

packages/cli/README.md
packages/cli/src/api/extract.js
packages/cli/src/api/parsers/txnativejson.js
packages/cli/src/commands/push.js
packages/cli/test/api/extract.txnativejson.test.js
packages/cli/test/fixtures/txnative.json

Adds support for `txjs-cli push source.json --parser=txnativejson` commands, to allow users to push content from JSON files, e.g. extracted from databases or other sources. 
The JSON format is following the CDS data payload format:
```
{
<key>: {
string: <string>,
meta: {
context: <string>
developer_comment: <string>,
character_limit: <number>,
tags: <array>,
occurrences: <array>,
}
}
<key>: { .. }
}
```
with `meta` field treated as optional.

@transifex/cli Add support for pushing JSON files

---

packages/angular/projects/tx-native-angular-sdk/README.md
packages/angular/projects/tx-native-angular-sdk/src/lib/interfaces.ts
packages/angular/projects/tx-native-angular-sdk/tests/translation.service.spec.ts
packages/cli/README.md
packages/cli/src/api/download.js
packages/cli/src/commands/pull.js
packages/cli/test/commands/pull.test.js
packages/native/README.md
packages/native/src/TxNative.js
packages/native/tests/renderer.test.js
packages/native/tests/t.test.js
packages/native/tests/tx.test.js

Update `@transifex/native` & `@transifex/cli` to support the new `filterStatus: "reviewed|proofread|finalized"` option, that can be used to only fetch phrases based on their translation status.
Compatible with [CDS 2.5.0](https://github.com/transifex/transifex-delivery/releases/tag/2.5.0).

Add support for filtering content by translation status

---

README.md
packages/cli/package.json
packages/cli/src/api/parsers/vue.js
packages/vue3/.eslintrc
packages/vue3/.npmignore
packages/vue3/README.md
packages/vue3/babel.config.js
packages/vue3/package.json
packages/vue3/rollup.config.js
packages/vue3/src/components/LanguagePicker.vue
packages/vue3/src/components/T.js
packages/vue3/src/components/UT.js
packages/vue3/src/index.js
packages/vue3/src/native.js
packages/vue3/tests/LanguagePicker.spec.js
packages/vue3/tests/T.spec.js
packages/vue3/tests/UT.spec.js

In order to support Vue3 we had to drop `vue-template-compiler`
in favor of `@vue/compiler-sfc` for compatibility reasons. This
way we can now support both Vue2 and Vue3.
Side effects
`vue/compiler-sfc` ast result is more cryptic than the previous
dependency, so we might need to revisit in the future and
use an alternative.

Add Vue3 support

---

packages/cli/src/api/parsers/angularHTML.js
packages/cli/test/api/extract.hashedkeys.test.js
packages/cli/test/api/extract.sourcekeys.test.js
packages/cli/test/fixtures/angular-template.html

Fixes issue where additional whitespaces in Angular pipe syntax causes the CLI not to pick up translation strings.
This is my first contribution here, let me know if anything is missing or needs to be changes.
closes #166

Add regex for additional whitespaces in Angular template pipe syntax in CLI

---

packages/cli/src/api/parsers/vue.js
packages/cli/test/api/extract.hashedkeys.test.js
packages/cli/test/api/extract.sourcekeys.test.js
packages/cli/test/fixtures/vuejs.vue

Fixes:
* `t` functions inside `v-if` were being ignored Now it utilises `branches` to understand if it's a condition and proceeds with parsing.
* Cases that a `t` expression would be sibling with an HTML element would be ignored. Type of `12` is added for parsing.
* Parsing of props.

Fix issue with Vue templates parsing

---

packages/cli/src/api/parsers/vue.js
packages/cli/test/fixtures/vuejs.vue

In a previous commit we included in the Vue parser the type `12` in visitors in order to parse some
simblings and pass the content to the BabelParser.
This resulted to simple text being parsed and Babel throwing an error when trying to parse for strings.
In this fix in case there are no `children` we use `traverseNode` to the `content` which should result to parsing all the things needed and causing no errors.

Revert change about additional type (Vue)

---

packages/cli/src/api/parsers/vue.js
packages/cli/test/fixtures/vuejs.vue

Some complex props were causing errors in
`babelExtractPhrases`. For now these are silenced
so the parsing can continue without any issues.

Better Vue props handling

---

packages/cli/package.json
packages/cli/src/commands/push.js
packages/cli/test/commands/push.test.js

This change show the relative path (related to the CLI execution) instead of full path.

Fix for relative path on verbose output in CLI

---

packages/angular/projects/tx-native-angular-sdk/src/lib/interfaces.ts
packages/angular/projects/tx-native-angular-sdk/tests/language-picker.component.spec.ts
packages/angular/projects/tx-native-angular-sdk/tests/translation.service.spec.ts
packages/native/src/index.d.ts

Bad types like `any` are so much worse than no types at all. But at least this would be correct types (mostly). #64

Implement Types for native

---

packages/cli/README.md
packages/cli/src/api/upload.js
packages/cli/src/commands/push.js

Update `txjs-cli push` with two additional parameters:
* `--do-not-keep-translations`: Remove translations in Transifex when the source string for an existing key changes.
* `--override-tags`: Replace all tags of strings in Transifex with the ones pushed using the CLI.

@transifex/cli: Add params for deleting translations & tags

---

packages/api/webpack.config.js
packages/dom/webpack.browser.js
packages/dom/webpack.node.js
packages/i18next/webpack.browser.js
packages/i18next/webpack.node.js
packages/jsonapi/webpack.config.js
packages/native/webpack.browser.js
packages/native/webpack.node.js

Set the webpack config `globalObject` to `this` to allow universal builds for both web and node.
This potentially fixes an issue with SSR related builds:
`ReferenceError: self is not defined`
Related: https://webpack.js.org/configuration/output/#outputglobalobject

Update globalObject webpack target

---

packages/cli/README.md
packages/cli/src/api/upload.js
packages/cli/src/commands/push.js
packages/native/README.md
packages/native/src/TxNative.js
packages/native/src/index.d.ts

Add CDS 4.x.x support for override-occurrences when pushing strings in both the SDK and the CLI.

CLI: Add override-occurences flag

---

packages/cli/src/api/parsers/angularHTML.js
packages/cli/test/api/extract.hashedkeys.test.js
packages/cli/test/api/extract.sourcekeys.test.js
packages/cli/test/fixtures/angular-template.html

Fixes issue inside `txjs-cli push` where an Angular template containing _any_ non-standard self-closing-tags causes the parser to silently fail and _no_ translation strings being picked up inside that template. More context in #193 
Closes #193

Add support for Angular 15 self-closing-tags inside txjs-cli push

---

packages/react/README.md
packages/react/src/hooks/useLanguages.js
packages/react/src/hooks/useLocale.js
packages/react/src/hooks/useT.js
packages/react/src/hooks/useTranslations.js
packages/react/src/utils/translateWithElements.jsx
packages/react/tests/useT.test.js

Addresses issue:  https://github.com/transifex/transifex-javascript/issues/182

Update React hooks to pass custom tx instance

---

packages/native/.eslintrc.json
packages/native/package.json
packages/native/src/TxNative.js
packages/native/tests/tx.test.js

Follow up on issue: https://github.com/transifex/transifex-javascript/issues/203
The scope is to try and reduce the bundle size of `@transifex/native` by taking the following actions:
- Replace `axios` with `fetch` when making requests.
- Add `browserslist` to reduce bundle size, by dropping support for outdated browsers.
Additionally the rewrite to using `fetch` is handling https://github.com/transifex/transifex-javascript/issues/200
- Add timeout on fetch requests

Optimize bundle size

---

packages/cli/src/api/parsers/vue.js
packages/cli/test/api/extract.hashedkeys.test.js
packages/cli/test/api/extract.sourcekeys.test.js
packages/cli/test/fixtures/vuejs.vue

Update @transifex/cli to parse the following Vue3 blocks:
```
<script setup>... </script>
```
Based on: https://github.com/transifex/transifex-javascript/pull/202

@transifex/cli: Detect Vue3 script setup

---

packages/api/src/transifexApi.d.ts

Related to: https://github.com/transifex/transifex-javascript/issues/198

@transifex/api Update TS declarations

---

packages/react/src/components/LanguagePicker.jsx
packages/react/src/components/T.jsx
packages/react/src/components/UT.jsx

React 18.3 added a [deprecation warning ](https://github.com/facebook/react/blob/main/CHANGELOG.md#1830-april-25-2024)for usage of defaultProps in functional components.
This PR replaces its usage with Javascript's default parameters.

Remove defaultProps from React package

---

packages/native/src/TxNative.js
packages/native/src/index.d.ts
packages/native/src/policies/PseudoTranslationPolicy.js
packages/native/src/policies/SourceStringPolicy.js

On Native code library, expose translation string params in the missing policies, similar to error policies.

TXNative: Expose params in missing policies

---

packages/native/package.json
packages/native/src/renderers/MessageFormatRenderer.js

Related to this [issue](https://github.com/transifex/transifex-javascript/issues/221)
We use this [package](https://github.com/messageformat/messageformat)  for localization. This package [doesn't adhere](https://github.com/messageformat/messageformat/issues/180) to CSP, which is why they need to include 'unsafe-eval'. The library maintainers [propose](https://github.com/messageformat/messageformat/issues/180) using this [alternative library](https://formatjs.io/docs/intl-messageformat/) instead.
The replacement of the library affects this core [method](https://github.com/transifex/transifex-javascript/blob/master/packages/native/src/renderers/MessageFormatRenderer.js).

Support CSP without unsafe-eval
